lib/bags_end_web/router.ex
defmodule BagsEndWeb.Router do
  use BagsEndWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BagsEndWeb do
    pipe_through :browser
    
    get "/sign-in", SessionController, :new
    post "/sign-in", SessionController, :create
    delete "sign-out", SessionController, :delete
    get "/", PageController, :index
    resources "/registrations", UserController, only: [:create, :new]
  end

  # Other scopes may use custom stacks.
  # scope "/api", BagsEndWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: BagsEndWeb.Telemetry
    end
  end
end

lib/bags_end_web/views/layout_view.ex
defmodule BagsEndWeb.LayoutView do
  use BagsEndWeb, :view
end

lib/bags_end_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>BagsEnd</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <nav>
      <%= if signed_in?(@conn) do %>
        <%= link "Sign Out", to: Routes.session_path(@conn, :delete), method: :delete %>
      <% else %>
        <%= link "Sign In", to: Routes.session_path(@conn, :new) %>
        <%= link "Sign up", to: Routes.user_path(@conn, :new) %>
      <% end %>
    </nav>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>